package com.smorenburgds.wifisync.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.smorenburgds.wifisync.dao.Wifi;

import com.smorenburgds.wifisync.dao.WifiDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wifiDaoConfig;

    private final WifiDao wifiDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wifiDaoConfig = daoConfigMap.get(WifiDao.class).clone();
        wifiDaoConfig.initIdentityScope(type);

        wifiDao = new WifiDao(wifiDaoConfig, this);

        registerDao(Wifi.class, wifiDao);
    }
    
    public void clear() {
        wifiDaoConfig.getIdentityScope().clear();
    }

    public WifiDao getWifiDao() {
        return wifiDao;
    }

}
